name: mirror:code

on:
  push:
    branches: [master]
    paths: ['starters/**', 'site/**']

jobs:
  mirror-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GRINDJS_BOT_TOKEN }}

      - name: mirror code
        run: ./.github/workflows/scripts/mirror-code.js
